services:
  postgres:
    container_name: marbyn_profile
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=marbyn_profile
      - POSTGRES_USER=superadmin
      - POSTGRES_PASSWORD=28a4CeC
    ports:
      - '5433:5433'
    volumes:
      - ./PersistanceLog/postgres-data:/var/lib/postgresql
    command:
      - -p 5433