services:
  postgres:
    container_name: marbyn_smartphone
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=marbyn_smartphone
      - POSTGRES_USER=superadmin
      - POSTGRES_PASSWORD=25$121Xz
    ports:
      - '5430:5430'
    volumes:
      - ./PersistanceLog/postgres-data:/var/lib/postgresql
    command:
      - -p 5430